# define the  workflow name
name: shell commands

# define the event
on: [pull_request]

# list the jobs/objects
jobs:  # each job runs in parallel on the virtual machine by default
  run-shell-python-commands:
    runs-on: ubuntu-latest
    steps:   # this is an array
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          sudo apt-get update
          sudo apt-get install nginx
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-python-commands"] # This force the second job to run after the first on finishes. (depend-on)
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
          
          


