name: Action Workflows

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Javascript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1 # can use @branch, versionId or commit (commitId is the safest way)
        with:
          who-to-greet: Lucas
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"

        