name: Action Workflows

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Set ENV
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
        #git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      # Let's automatically clone a repos in our working env
      - name: Checkout
        uses: actions/checkout@v1
        # we can also manually code this step using commit ID & Token
      
      - name: List Files after Checkout
        run: |
          pwd
          ls -a
      - name: Simple Javascript Action
        id: greet
        uses: actions/hello-world-javascript-action@v1 # can use @branch, versionId or commit (commitId is the safest way)
        with:
          who-to-greet: Lucas
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"

        