name: create docker image from docker file

on: [push, pull_request]

jobs:
  run-docker-commands:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script to install docker
        run: |
          sudo apt-get update
          sudo apt-get install \
          ca-certificates \
          curl \
          gnupg \
          lsb-release
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
          echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

      - name: test docker
        run: sudo docker run hello-world
      - name: pull an image
        run: sudo docker pull nginx

 
