# define the  workflow name
name: shell commands

# define the event
on: [push]

# list the jobs/objects
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:   # this is an array
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          sudo apt-get update
          sudo apt-get install nginx
      - name: python commands
        run: |
          import platform
          print(platform.processor)
        shell: python
          
          
          


